spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
        format_sql: true

  flyway:
    enabled: ${FLYWAY_ENABLED}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE}
    locations: ${FLYWAY_LOCATIONS}

server:
  port: ${SERVER_PORT}


security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:86400000}

