version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-java-app
    ports:
      - "8001:8001"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: unless-stopped
