spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO